# Generated by Django 3.0 on 2019-12-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.TextField(blank=True, default=''),
        ),
    ]
